### ISSUE TITLE
Third Finger Not Detected

### ISSUE THREAD

**Issue by aditisstillalive** [ClementGre/ThreeFingerDragOnWindows#61]
Hi, this is my first time writing an issue on github, hopefully, I provided sufficient information.

I have 2 laptops on which I installed this app, the other laptop was working fine, but on this laptop, it doesn't seem to be working no matter which version I installed.

Laptop model: Lenovo Thinkpad E14 Gen 2
OS: Windows 11 (Version 23H2)

If I understand correctly, the main page of the app is supposed to be showing the number of fingers touching the touchpad by ID, however, when I tried to touch it, the following were showing:

One finger
![image](https://github.com/ClementGre/ThreeFingerDragOnWindows/assets/12996680/c2805901-74b4-43e2-a67c-ae19bd4bb163)

Two fingers
![image](https://github.com/ClementGre/ThreeFingerDragOnWindows/assets/12996680/b4adcc9b-9d4b-4861-9275-270ca679391f)

Three fingers (somehow as soon as my third finger touched the trackpad, the page only showing one ID instead of three)
![image](https://github.com/ClementGre/ThreeFingerDragOnWindows/assets/12996680/6dc78823-2619-4550-922b-20bb114ce777)

I'm sure I have followed all the settings for Windows touchpad/gesture and the three finger drag app itself since I have it installed and working correctly in my other laptop.

Log:
[Logs_ThreeFingerDragOnWindows.txt](https://github.com/ClementGre/ThreeFingerDragOnWindows/files/15446076/Logs_ThreeFingerDragOnWindows.txt)

**Comment by ClementGre** [comment]
Hi and thank you for the detailed bug report.
In your logs the app is not receiving any input (a finger) with an ID other than 0 or 1.
This is a bug of the raw input parser I am using, and other users have similar issues with input detection.

I will soon try to redevelop the raw input parsing mechanics and hopefully it will fix all these bugs. Meanwhile I can't do anything to make the app work on your computer.

Thank you !

**Comment by ClementGre** [comment]
I just released a new version of TFDOW that should fix some bugs regarding the touchpad raw input parsing for touchpads that send reports "sequentially". It might fix this issue.

Can you try again on the [v2.0.5](https://github.com/ClementGre/ThreeFingerDragOnWindows/releases/tag/2.0.5) ([Microsoft Store](https://apps.microsoft.com/detail/threefingersdragonwindows/9MSX91WQCM2V)).
If you still have issues, you can share again the log file.

**Comment by ClementGre** [comment]
I just released v2.0.6. It should fix this issue. Can you try it out?
See [v2.0.6](https://github.com/ClementGre/ThreeFingerDragOnWindows/releases/tag/2.0.6) | [MS Store](https://apps.microsoft.com/detail/9MSX91WQCM2V?)

**Comment by aditisstillalive** [comment]
Thank you for your hard work, but unfortunately, it still doesn't detect the third finger for me. 
I couldn't find log entries for ID: 2; only found ID: 0 and ID: 1. I have attached the log file just in case.

But anyway thank you for the effort, hopefully, the update fixed issues reported by the other users.
[Logs_ThreeFingerDragOnWindows.txt](https://github.com/user-attachments/files/16408651/Logs_ThreeFingerDragOnWindows.txt)

**Comment by ClementGre** [comment]
Thank you, your touchpad has bizarre behaviour as it doesn't list the same number of contacts as the provided contact count. Then the change I made in v2.0.6 is to take only into account the provided contact count and make sure the contacts lists always have the matching length (duplicating or removing contacts if needed).
It seems to work well on your touchpad, but now, the issue is that your touchpad reports a contact count of 2 most of the time (search for cC2), while there are only a few cC1 (1 finger on the touchpad). Then, the drag cannot start as it has to be a 1 fingers to 3 fingers transition (if starting to scroll with two fingers and then adding a third finger, this will not start the drag).

Can you try to switch from one finger to three fingers directly (or from 0 to 3 fingers). The goal is to have a cC1 report right before a cC3 report, or a cC3 report which is separated from the last report by some time. (In fact, it might work if a cC2 report appears between a cC1 and a cC3, but there should not be too much)

**Comment by aditisstillalive** [comment]
sorry for troubling you :( 

I've tried both tests you mentioned, the first one is from 1 to 3 and the next one is from 0 to 3 (and I drag my fingers after each test just to make sure).
[Logs_ThreeFingerDragOnWindows.txt](https://github.com/user-attachments/files/16410192/Logs_ThreeFingerDragOnWindows.txt)

**Comment by Masse85** [comment]
Hi, I have a similar laptop and have the identical issue, I've found that I need to have FOUR fingers on the touchpad for it to be recognised as 3 fingers, and sure enough if I use four fingers to drag it does work, somewhat erratically. 

I hope this information can help diagnose the issue, thanks.
